# `pandas.errors.PossibleDataLossError`

> 原文：[`pandas.pydata.org/docs/reference/api/pandas.errors.PossibleDataLossError.html`](https://pandas.pydata.org/docs/reference/api/pandas.errors.PossibleDataLossError.html)

```py
exception pandas.errors.PossibleDataLossError
```

当已经打开一个 HDFStore 文件时尝试打开时引发的异常。

例子

```py
>>> store = pd.HDFStore('my-store', 'a') 
>>> store.open("w") 
... # PossibleDataLossError: Re-opening the file [my-store] with mode [a]... 
```
