# `pandas.errors.InvalidComparison`

> 原文：[`pandas.pydata.org/docs/reference/api/pandas.errors.InvalidComparison.html`](https://pandas.pydata.org/docs/reference/api/pandas.errors.InvalidComparison.html)

```py
exception pandas.errors.InvalidComparison
```

由 _validate_comparison_value 引发的异常，表示比较无效。

注意

这是一个内部错误。
