# `scipy.constants.ConstantWarning`

> [`docs.scipy.org/doc/scipy-1.12.0/reference/generated/scipy.constants.ConstantWarning.html#scipy.constants.ConstantWarning`](https://docs.scipy.org/doc/scipy-1.12.0/reference/generated/scipy.constants.ConstantWarning.html#scipy.constants.ConstantWarning)

```py
exception scipy.constants.ConstantWarning
```

访问一个不再包含在当前 CODATA 数据集中的常数。

```py
with_traceback()
```

Exception.with_traceback(tb) – 将 self.__traceback__ 设置为 tb 并返回 self。
