# numpy.geterrcall

> 原文：[`numpy.org/doc/1.26/reference/generated/numpy.geterrcall.html`](https://numpy.org/doc/1.26/reference/generated/numpy.geterrcall.html)

```py
numpy.geterrcall()
```

返回当前用于浮点错误的回调函数。

当浮点错误（“divide”、“over”、“under”或“invalid”之一）的错误处理设置为“call”或“log”时，返回使用[`geterrcall`](https://numpy.org/doc/1.26/reference/generated/numpy.geterrcall.html)设置的函数或日志实例。此函数或日志实例已通过[`seterrcall`](https://numpy.org/doc/1.26/reference/generated/numpy.seterrcall.html)设置。

返回值：

**errobj**可调用对象、日志实例或 None

当前错误处理程序。如果未通过[`seterrcall`](https://numpy.org/doc/1.26/reference/generated/numpy.seterrcall.html)设置处理程序，则返回 None。

另请参见

[`seterrcall`](https://numpy.org/doc/1.26/reference/generated/numpy.seterrcall.html)、[`seterr`](https://numpy.org/doc/1.26/reference/generated/numpy.seterr.html)和[`geterr`](https://numpy.org/doc/1.26/reference/generated/numpy.geterr.html)

注意事项

关于浮点异常类型和处理选项的完整文档，请参阅[`seterr`](https://numpy.org/doc/1.26/reference/generated/numpy.seterr.html)。

示例

```py
>>> np.geterrcall()  # we did not yet set a handler, returns None 
```

```py
>>> oldsettings = np.seterr(all='call')
>>> def err_handler(type, flag):
...     print("Floating point error (%s), with flag %s" % (type, flag))
>>> oldhandler = np.seterrcall(err_handler)
>>> np.array([1, 2, 3]) / 0.0
Floating point error (divide by zero), with flag 1
array([inf, inf, inf]) 
```

```py
>>> cur_handler = np.geterrcall()
>>> cur_handler is err_handler
True 
```
