- en: scipy.linalg.LinAlgWarning
  id: totrans-0
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: scipy.linalg.LinAlgWarning
- en: Original text：[https://docs.scipy.org/doc/scipy-1.12.0/reference/generated/scipy.linalg.LinAlgWarning.html#scipy.linalg.LinAlgWarning](https://docs.scipy.org/doc/scipy-1.12.0/reference/generated/scipy.linalg.LinAlgWarning.html#scipy.linalg.LinAlgWarning)
  id: totrans-1
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 原文：[https://docs.scipy.org/doc/scipy-1.12.0/reference/generated/scipy.linalg.LinAlgWarning.html#scipy.linalg.LinAlgWarning](https://docs.scipy.org/doc/scipy-1.12.0/reference/generated/scipy.linalg.LinAlgWarning.html#scipy.linalg.LinAlgWarning)
- en: '[PRE0]'
  id: totrans-2
  prefs: []
  type: TYPE_PRE
  zh: '[PRE0]'
- en: The warning emitted when a linear algebra related operation is close to fail
    conditions of the algorithm or loss of accuracy is expected.
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: 当线性代数相关操作接近算法失效条件或预计精度损失时发出警告。
- en: '[PRE1]'
  id: totrans-4
  prefs: []
  type: TYPE_PRE
  zh: '[PRE1]'
- en: Exception.with_traceback(tb) – set self.__traceback__ to tb and return self.
  id: totrans-5
  prefs: []
  type: TYPE_NORMAL
  zh: '`Exception.with_traceback(tb)` – 将 self.__traceback__ 设置为 tb 并返回 self。'
