- en: pandas.errors.OutOfBoundsDatetime
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 原文：[https://pandas.pydata.org/docs/reference/api/pandas.errors.OutOfBoundsDatetime.html](https://pandas.pydata.org/docs/reference/api/pandas.errors.OutOfBoundsDatetime.html)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: '[PRE0]'
  prefs: []
  type: TYPE_PRE
- en: Raised when the datetime is outside the range that can be represented.
  prefs: []
  type: TYPE_NORMAL
- en: Examples
  prefs: []
  type: TYPE_NORMAL
- en: '[PRE1]'
  prefs: []
  type: TYPE_PRE
