- en: What’s new in 1.2.1 (January 20, 2021)
  id: totrans-0
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 1.2.1 版本的新增内容（2021年1月20日）
- en: 原文：[https://pandas.pydata.org/docs/whatsnew/v1.2.1.html](https://pandas.pydata.org/docs/whatsnew/v1.2.1.html)
  id: totrans-1
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 原文：[https://pandas.pydata.org/docs/whatsnew/v1.2.1.html](https://pandas.pydata.org/docs/whatsnew/v1.2.1.html)
- en: These are the changes in pandas 1.2.1\. See [Release notes](index.html#release)
    for a full changelog including other versions of pandas.
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 这些是 pandas 1.2.1 版本的更改。查看[发布说明](index.html#release)以获取包括 pandas 其他版本在内的完整更改日志。
- en: '## Fixed regressions'
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: '## 修复的回归问题'
- en: Fixed regression in [`to_csv()`](../reference/api/pandas.DataFrame.to_csv.html#pandas.DataFrame.to_csv
    "pandas.DataFrame.to_csv") that created corrupted zip files when there were more
    rows than `chunksize` ([GH 38714](https://github.com/pandas-dev/pandas/issues/38714))
  id: totrans-4
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了当行数超过`chunksize`时，[`to_csv()`](../reference/api/pandas.DataFrame.to_csv.html#pandas.DataFrame.to_csv
    "pandas.DataFrame.to_csv")创建损坏的 zip 文件的回归问题 ([GH 38714](https://github.com/pandas-dev/pandas/issues/38714))
- en: Fixed regression in [`to_csv()`](../reference/api/pandas.DataFrame.to_csv.html#pandas.DataFrame.to_csv
    "pandas.DataFrame.to_csv") opening `codecs.StreamReaderWriter` in binary mode
    instead of in text mode ([GH 39247](https://github.com/pandas-dev/pandas/issues/39247))
  id: totrans-5
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了在将 [`to_csv()`](../reference/api/pandas.DataFrame.to_csv.html#pandas.DataFrame.to_csv
    "pandas.DataFrame.to_csv") 中的 `codecs.StreamReaderWriter` 以二进制模式而不是文本模式打开的回归问题
    ([GH 39247](https://github.com/pandas-dev/pandas/issues/39247))
- en: Fixed regression in [`read_csv()`](../reference/api/pandas.read_csv.html#pandas.read_csv
    "pandas.read_csv") and other read functions were the encoding error policy (`errors`)
    did not default to `"replace"` when no encoding was specified ([GH 38989](https://github.com/pandas-dev/pandas/issues/38989))
  id: totrans-6
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了在未指定编码时，[`read_csv()`](../reference/api/pandas.read_csv.html#pandas.read_csv
    "pandas.read_csv") 和其他读取函数中编码错误策略 (`errors`) 未默认为 `"replace"` 的回归问题 ([GH 38989](https://github.com/pandas-dev/pandas/issues/38989))
- en: Fixed regression in [`read_excel()`](../reference/api/pandas.read_excel.html#pandas.read_excel
    "pandas.read_excel") with non-rawbyte file handles ([GH 38788](https://github.com/pandas-dev/pandas/issues/38788))
  id: totrans-7
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了对非原始字节文件句柄的[`read_excel()`](../reference/api/pandas.read_excel.html#pandas.read_excel
    "pandas.read_excel")中的回归问题 ([GH 38788](https://github.com/pandas-dev/pandas/issues/38788))
- en: Fixed regression in [`DataFrame.to_stata()`](../reference/api/pandas.DataFrame.to_stata.html#pandas.DataFrame.to_stata
    "pandas.DataFrame.to_stata") not removing the created file when an error occurred
    ([GH 39202](https://github.com/pandas-dev/pandas/issues/39202))
  id: totrans-8
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了在发生错误时，[`DataFrame.to_stata()`](../reference/api/pandas.DataFrame.to_stata.html#pandas.DataFrame.to_stata
    "pandas.DataFrame.to_stata") 未删除创建的文件的回归问题 ([GH 39202](https://github.com/pandas-dev/pandas/issues/39202))
- en: Fixed regression in `DataFrame.__setitem__` raising `ValueError` when expanding
    [`DataFrame`](../reference/api/pandas.DataFrame.html#pandas.DataFrame "pandas.DataFrame")
    and new column is from type `"0 - name"` ([GH 39010](https://github.com/pandas-dev/pandas/issues/39010))
  id: totrans-9
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了在扩展 [`DataFrame`](../reference/api/pandas.DataFrame.html#pandas.DataFrame
    "pandas.DataFrame") 并且新列类型为 `"0 - name"` 时，`DataFrame.__setitem__` 引发 `ValueError`
    的回归问题 ([GH 39010](https://github.com/pandas-dev/pandas/issues/39010))
- en: Fixed regression in setting with [`DataFrame.loc()`](../reference/api/pandas.DataFrame.loc.html#pandas.DataFrame.loc
    "pandas.DataFrame.loc") raising `ValueError` when [`DataFrame`](../reference/api/pandas.DataFrame.html#pandas.DataFrame
    "pandas.DataFrame") has unsorted [`MultiIndex`](../reference/api/pandas.MultiIndex.html#pandas.MultiIndex
    "pandas.MultiIndex") columns and indexer is a scalar ([GH 38601](https://github.com/pandas-dev/pandas/issues/38601))
  id: totrans-10
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了当 [`DataFrame`](../reference/api/pandas.DataFrame.html#pandas.DataFrame "pandas.DataFrame")
    有未排序的 [`MultiIndex`](../reference/api/pandas.MultiIndex.html#pandas.MultiIndex
    "pandas.MultiIndex") 列且索引器为标量时，使用 [`DataFrame.loc()`](../reference/api/pandas.DataFrame.loc.html#pandas.DataFrame.loc
    "pandas.DataFrame.loc") 设置时引发 `ValueError` 的回归问题 ([GH 38601](https://github.com/pandas-dev/pandas/issues/38601))
- en: Fixed regression in setting with [`DataFrame.loc()`](../reference/api/pandas.DataFrame.loc.html#pandas.DataFrame.loc
    "pandas.DataFrame.loc") raising `KeyError` with [`MultiIndex`](../reference/api/pandas.MultiIndex.html#pandas.MultiIndex
    "pandas.MultiIndex") and list-like columns indexer enlarging [`DataFrame`](../reference/api/pandas.DataFrame.html#pandas.DataFrame
    "pandas.DataFrame") ([GH 39147](https://github.com/pandas-dev/pandas/issues/39147))
  id: totrans-11
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了在使用 [`DataFrame.loc()`](../reference/api/pandas.DataFrame.loc.html#pandas.DataFrame.loc
    "pandas.DataFrame.loc") 设置时，对具有 [`MultiIndex`](../reference/api/pandas.MultiIndex.html#pandas.MultiIndex
    "pandas.MultiIndex") 和类似列表的列索引器进行扩展 [`DataFrame`](../reference/api/pandas.DataFrame.html#pandas.DataFrame
    "pandas.DataFrame") 时引发 `KeyError` 的回归问题 ([GH 39147](https://github.com/pandas-dev/pandas/issues/39147))
- en: Fixed regression in [`groupby()`](../reference/api/pandas.DataFrame.groupby.html#pandas.DataFrame.groupby
    "pandas.DataFrame.groupby") with [`Categorical`](../reference/api/pandas.Categorical.html#pandas.Categorical
    "pandas.Categorical") grouping column not showing unused categories for `grouped.indices`
    ([GH 38642](https://github.com/pandas-dev/pandas/issues/38642))
  id: totrans-12
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了 [`groupby()`](../reference/api/pandas.DataFrame.groupby.html#pandas.DataFrame.groupby
    "pandas.DataFrame.groupby") 中的回归问题，使用 [`Categorical`](../reference/api/pandas.Categorical.html#pandas.Categorical
    "pandas.Categorical") 分组列时，`grouped.indices` 不显示未使用的类别 ([GH 38642](https://github.com/pandas-dev/pandas/issues/38642))
- en: Fixed regression in [`DataFrameGroupBy.sem()`](../reference/api/pandas.core.groupby.DataFrameGroupBy.sem.html#pandas.core.groupby.DataFrameGroupBy.sem
    "pandas.core.groupby.DataFrameGroupBy.sem") and [`SeriesGroupBy.sem()`](../reference/api/pandas.core.groupby.SeriesGroupBy.sem.html#pandas.core.groupby.SeriesGroupBy.sem
    "pandas.core.groupby.SeriesGroupBy.sem") where the presence of non-numeric columns
    would cause an error instead of being dropped ([GH 38774](https://github.com/pandas-dev/pandas/issues/38774))
  id: totrans-13
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了 [`DataFrameGroupBy.sem()`](../reference/api/pandas.core.groupby.DataFrameGroupBy.sem.html#pandas.core.groupby.DataFrameGroupBy.sem
    "pandas.core.groupby.DataFrameGroupBy.sem") 和 [`SeriesGroupBy.sem()`](../reference/api/pandas.core.groupby.SeriesGroupBy.sem.html#pandas.core.groupby.SeriesGroupBy.sem
    "pandas.core.groupby.SeriesGroupBy.sem") 中的回归问题，其中存在非数值列会导致错误而不是被删除 ([GH 38774](https://github.com/pandas-dev/pandas/issues/38774))
- en: Fixed regression in [`DataFrameGroupBy.diff()`](../reference/api/pandas.core.groupby.DataFrameGroupBy.diff.html#pandas.core.groupby.DataFrameGroupBy.diff
    "pandas.core.groupby.DataFrameGroupBy.diff") raising for `int8` and `int16` columns
    ([GH 39050](https://github.com/pandas-dev/pandas/issues/39050))
  id: totrans-14
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了 [`DataFrameGroupBy.diff()`](../reference/api/pandas.core.groupby.DataFrameGroupBy.diff.html#pandas.core.groupby.DataFrameGroupBy.diff
    "pandas.core.groupby.DataFrameGroupBy.diff") 中的回归问题，对于 `int8` 和 `int16` 列引发错误
    ([GH 39050](https://github.com/pandas-dev/pandas/issues/39050))
- en: Fixed regression in [`DataFrame.groupby()`](../reference/api/pandas.DataFrame.groupby.html#pandas.DataFrame.groupby
    "pandas.DataFrame.groupby") when aggregating an `ExtensionDType` that could fail
    for non-numeric values ([GH 38980](https://github.com/pandas-dev/pandas/issues/38980))
  id: totrans-15
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了 [`DataFrame.groupby()`](../reference/api/pandas.DataFrame.groupby.html#pandas.DataFrame.groupby
    "pandas.DataFrame.groupby") 中的回归问题，聚合 `ExtensionDType` 时，对于非数值值可能会失败 ([GH 38980](https://github.com/pandas-dev/pandas/issues/38980))
- en: Fixed regression in [`Rolling.skew()`](../reference/api/pandas.core.window.rolling.Rolling.skew.html#pandas.core.window.rolling.Rolling.skew
    "pandas.core.window.rolling.Rolling.skew") and [`Rolling.kurt()`](../reference/api/pandas.core.window.rolling.Rolling.kurt.html#pandas.core.window.rolling.Rolling.kurt
    "pandas.core.window.rolling.Rolling.kurt") modifying the object inplace ([GH 38908](https://github.com/pandas-dev/pandas/issues/38908))
  id: totrans-16
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了 [`Rolling.skew()`](../reference/api/pandas.core.window.rolling.Rolling.skew.html#pandas.core.window.rolling.Rolling.skew
    "pandas.core.window.rolling.Rolling.skew") 和 [`Rolling.kurt()`](../reference/api/pandas.core.window.rolling.Rolling.kurt.html#pandas.core.window.rolling.Rolling.kurt
    "pandas.core.window.rolling.Rolling.kurt") 中的回归问题，这些问题会直接修改对象本身 ([GH 38908](https://github.com/pandas-dev/pandas/issues/38908))
- en: Fixed regression in [`DataFrame.any()`](../reference/api/pandas.DataFrame.any.html#pandas.DataFrame.any
    "pandas.DataFrame.any") and [`DataFrame.all()`](../reference/api/pandas.DataFrame.all.html#pandas.DataFrame.all
    "pandas.DataFrame.all") not returning a result for tz-aware `datetime64` columns
    ([GH 38723](https://github.com/pandas-dev/pandas/issues/38723))
  id: totrans-17
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了 [`DataFrame.any()`](../reference/api/pandas.DataFrame.any.html#pandas.DataFrame.any
    "pandas.DataFrame.any") 和 [`DataFrame.all()`](../reference/api/pandas.DataFrame.all.html#pandas.DataFrame.all
    "pandas.DataFrame.all") 中的回归问题，不会为 tz-aware `datetime64` 列返回结果 ([GH 38723](https://github.com/pandas-dev/pandas/issues/38723))
- en: Fixed regression in [`DataFrame.apply()`](../reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply
    "pandas.DataFrame.apply") with `axis=1` using str accessor in apply function ([GH
    38979](https://github.com/pandas-dev/pandas/issues/38979))
  id: totrans-18
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了 [`DataFrame.apply()`](../reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply
    "pandas.DataFrame.apply") 中的回归问题，当 `axis=1` 时，在应用函数中使用 str 访问器 ([GH 38979](https://github.com/pandas-dev/pandas/issues/38979))
- en: Fixed regression in [`DataFrame.replace()`](../reference/api/pandas.DataFrame.replace.html#pandas.DataFrame.replace
    "pandas.DataFrame.replace") raising `ValueError` when [`DataFrame`](../reference/api/pandas.DataFrame.html#pandas.DataFrame
    "pandas.DataFrame") has dtype `bytes` ([GH 38900](https://github.com/pandas-dev/pandas/issues/38900))
  id: totrans-19
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了 [`DataFrame.replace()`](../reference/api/pandas.DataFrame.replace.html#pandas.DataFrame.replace
    "pandas.DataFrame.replace") 中的回归问题，当 [`DataFrame`](../reference/api/pandas.DataFrame.html#pandas.DataFrame
    "pandas.DataFrame") 的 dtype 为 `bytes` 时引发 `ValueError` ([GH 38900](https://github.com/pandas-dev/pandas/issues/38900))
- en: Fixed regression in [`Series.fillna()`](../reference/api/pandas.Series.fillna.html#pandas.Series.fillna
    "pandas.Series.fillna") that raised `RecursionError` with `datetime64[ns, UTC]`
    dtype ([GH 38851](https://github.com/pandas-dev/pandas/issues/38851))
  id: totrans-20
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了一个问题，在使用 `datetime64[ns, UTC]` 数据类型时引发 `RecursionError` 的 [`Series.fillna()`](../reference/api/pandas.Series.fillna.html#pandas.Series.fillna
    "pandas.Series.fillna")（[GH 38851](https://github.com/pandas-dev/pandas/issues/38851)）
- en: Fixed regression in comparisons between `NaT` and `datetime.date` objects incorrectly
    returning `True` ([GH 39151](https://github.com/pandas-dev/pandas/issues/39151))
  id: totrans-21
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了一个问题，在 `NaT` 和 `datetime.date` 对象之间的比较中错误地返回 `True`（[GH 39151](https://github.com/pandas-dev/pandas/issues/39151)）
- en: Fixed regression in calling NumPy `accumulate()` ufuncs on DataFrames, e.g.
    `np.maximum.accumulate(df)` ([GH 39259](https://github.com/pandas-dev/pandas/issues/39259))
  id: totrans-22
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了一个问题，在数据帧上调用 NumPy `accumulate()` ufuncs 时引发错误，例如 `np.maximum.accumulate(df)`（[GH
    39259](https://github.com/pandas-dev/pandas/issues/39259)）
- en: Fixed regression in repr of float-like strings of an `object` dtype having trailing
    0’s truncated after the decimal ([GH 38708](https://github.com/pandas-dev/pandas/issues/38708))
  id: totrans-23
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了一个问题，在 `object` 数据类型的类似浮点数的字符串的表示中，小数点后的尾部 `0` 被截断了（[GH 38708](https://github.com/pandas-dev/pandas/issues/38708)）
- en: Fixed regression that raised `AttributeError` with PyArrow versions [0.16.0,
    1.0.0) ([GH 38801](https://github.com/pandas-dev/pandas/issues/38801))
  id: totrans-24
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了一个问题，即在 PyArrow 版本 [0.16.0, 1.0.0) 中引发 `AttributeError` 的回归问题（[GH 38801](https://github.com/pandas-dev/pandas/issues/38801)）
- en: Fixed regression in [`pandas.testing.assert_frame_equal()`](../reference/api/pandas.testing.assert_frame_equal.html#pandas.testing.assert_frame_equal
    "pandas.testing.assert_frame_equal") raising `TypeError` with `check_like=True`
    when [`Index`](../reference/api/pandas.Index.html#pandas.Index "pandas.Index")
    or columns have mixed dtype ([GH 39168](https://github.com/pandas-dev/pandas/issues/39168))
  id: totrans-25
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了一个问题，在 [`pandas.testing.assert_frame_equal()`](../reference/api/pandas.testing.assert_frame_equal.html#pandas.testing.assert_frame_equal
    "pandas.testing.assert_frame_equal") 使用 `check_like=True` 时引发 `TypeError`，当 [`Index`](../reference/api/pandas.Index.html#pandas.Index
    "pandas.Index") 或列具有混合数据类型时（[GH 39168](https://github.com/pandas-dev/pandas/issues/39168))
- en: 'We have reverted a commit that resulted in several plotting related regressions
    in pandas 1.2.0 ([GH 38969](https://github.com/pandas-dev/pandas/issues/38969),
    [GH 38736](https://github.com/pandas-dev/pandas/issues/38736), [GH 38865](https://github.com/pandas-dev/pandas/issues/38865),
    [GH 38947](https://github.com/pandas-dev/pandas/issues/38947) and [GH 39126](https://github.com/pandas-dev/pandas/issues/39126)).
    As a result, bugs reported as fixed in pandas 1.2.0 related to inconsistent tick
    labeling in bar plots are again present ([GH 26186](https://github.com/pandas-dev/pandas/issues/26186)
    and [GH 11465](https://github.com/pandas-dev/pandas/issues/11465))  ## Calling
    NumPy ufuncs on non-aligned DataFrames'
  id: totrans-26
  prefs: []
  type: TYPE_NORMAL
  zh: '我们已经撤销了一个提交，在 pandas 1.2.0 中导致了几个与绘图相关的回归问题（[GH 38969](https://github.com/pandas-dev/pandas/issues/38969)，[GH
    38736](https://github.com/pandas-dev/pandas/issues/38736)，[GH 38865](https://github.com/pandas-dev/pandas/issues/38865)，[GH
    38947](https://github.com/pandas-dev/pandas/issues/38947) 和 [GH 39126](https://github.com/pandas-dev/pandas/issues/39126)）。因此，在
    pandas 1.2.0 中报告为修复的与条形图中不一致的刻度标签相关的错误再次存在（[GH 26186](https://github.com/pandas-dev/pandas/issues/26186)
    和 [GH 11465](https://github.com/pandas-dev/pandas/issues/11465))  ## 在非对齐的数据帧上调用
    NumPy ufuncs'
- en: 'Before pandas 1.2.0, calling a NumPy ufunc on non-aligned DataFrames (or DataFrame
    / Series combination) would ignore the indices, only match the inputs by shape,
    and use the index/columns of the first DataFrame for the result:'
  id: totrans-27
  prefs: []
  type: TYPE_NORMAL
  zh: 在 pandas 1.2.0 之前，在非对齐的数据帧（或 DataFrame / Series 组合）上调用 NumPy ufunc 将忽略索引，只匹配形状相同的输入，并使用结果的第一个数据帧的索引/列：
- en: '[PRE0]'
  id: totrans-28
  prefs: []
  type: TYPE_PRE
  zh: '[PRE0]'
- en: 'This contrasts with how other pandas operations work, which first align the
    inputs:'
  id: totrans-29
  prefs: []
  type: TYPE_NORMAL
  zh: 这与其他 pandas 操作的工作方式相反，其他 pandas 操作首先对齐输入：
- en: '[PRE1]'
  id: totrans-30
  prefs: []
  type: TYPE_PRE
  zh: '[PRE1]'
- en: In pandas 1.2.0, we refactored how NumPy ufuncs are called on DataFrames, and
    this started to align the inputs first ([GH 39184](https://github.com/pandas-dev/pandas/issues/39184)),
    as happens in other pandas operations and as it happens for ufuncs called on Series
    objects.
  id: totrans-31
  prefs: []
  type: TYPE_NORMAL
  zh: 在 pandas 1.2.0 中，我们重构了如何在数据帧上调用 NumPy ufuncs，并且这开始首先对齐输入（[GH 39184](https://github.com/pandas-dev/pandas/issues/39184)），就像其他
    pandas 操作和对 Series 对象调用的 ufuncs 一样。
- en: For pandas 1.2.1, we restored the previous behaviour to avoid a breaking change,
    but the above example of `np.add(df1, df2)` with non-aligned inputs will now to
    raise a warning, and a future pandas 2.0 release will start aligning the inputs
    first ([GH 39184](https://github.com/pandas-dev/pandas/issues/39184)). Calling
    a NumPy ufunc on Series objects (eg `np.add(s1, s2)`) already aligns and continues
    to do so.
  id: totrans-32
  prefs: []
  type: TYPE_NORMAL
  zh: 对于 pandas 1.2.1，我们恢复了以避免破坏性更改，但上述使用非对齐输入的 `np.add(df1, df2)` 的示例现在将会引发警告，而未来的
    pandas 2.0 版本将首先对齐输入。在 Series 对象上调用 NumPy ufunc（例如 `np.add(s1, s2)`）已经对齐并将继续如此。
- en: 'To avoid the warning and keep the current behaviour of ignoring the indices,
    convert one of the arguments to a NumPy array:'
  id: totrans-33
  prefs: []
  type: TYPE_NORMAL
  zh: 为了避免警告并保持当前忽略索引的行为，将其中一个参数转换为 NumPy 数组：
- en: '[PRE2]'
  id: totrans-34
  prefs: []
  type: TYPE_PRE
  zh: '[PRE2]'
- en: 'To obtain the future behaviour and silence the warning, you can align manually
    before passing the arguments to the ufunc:'
  id: totrans-35
  prefs: []
  type: TYPE_NORMAL
  zh: 若要获得未来行为并消除警告，您可以在将参数传递给 ufunc 之前手动对齐：
- en: '[PRE3]  ## Bug fixes'
  id: totrans-36
  prefs: []
  type: TYPE_NORMAL
  zh: '[PRE3]  ## 错误修复'
- en: Bug in [`read_csv()`](../reference/api/pandas.read_csv.html#pandas.read_csv
    "pandas.read_csv") with `float_precision="high"` caused segfault or wrong parsing
    of long exponent strings. This resulted in a regression in some cases as the default
    for `float_precision` was changed in pandas 1.2.0 ([GH 38753](https://github.com/pandas-dev/pandas/issues/38753))
  id: totrans-37
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 在 pandas 1.2.0 中更改了 `float_precision` 的默认值后，[`read_csv()`](../reference/api/pandas.read_csv.html#pandas.read_csv
    "pandas.read_csv") 中的一个 bug 使用 `float_precision="high"` 导致长指数字符串的段错误或错误解析。这在某些情况下导致了回归
    ([GH 38753](https://github.com/pandas-dev/pandas/issues/38753))
- en: Bug in [`read_csv()`](../reference/api/pandas.read_csv.html#pandas.read_csv
    "pandas.read_csv") not closing an opened file handle when a `csv.Error` or `UnicodeDecodeError`
    occurred while initializing ([GH 39024](https://github.com/pandas-dev/pandas/issues/39024))
  id: totrans-38
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 在初始化时发生`csv.Error`或`UnicodeDecodeError`时，[`read_csv()`](../reference/api/pandas.read_csv.html#pandas.read_csv
    "pandas.read_csv")中的一个 bug 未关闭已打开的文件句柄 ([GH 39024](https://github.com/pandas-dev/pandas/issues/39024))
- en: 'Bug in [`pandas.testing.assert_index_equal()`](../reference/api/pandas.testing.assert_index_equal.html#pandas.testing.assert_index_equal
    "pandas.testing.assert_index_equal") raising `TypeError` with `check_order=False`
    when [`Index`](../reference/api/pandas.Index.html#pandas.Index "pandas.Index")
    has mixed dtype ([GH 39168](https://github.com/pandas-dev/pandas/issues/39168))  ##
    Other'
  id: totrans-39
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: '当 [`Index`](../reference/api/pandas.Index.html#pandas.Index "pandas.Index")
    具有混合数据类型时，[`pandas.testing.assert_index_equal()`](../reference/api/pandas.testing.assert_index_equal.html#pandas.testing.assert_index_equal
    "pandas.testing.assert_index_equal") 中的 bug 在 `check_order=False` 时引发 `TypeError`
    ([GH 39168](https://github.com/pandas-dev/pandas/issues/39168))  ## 其他'
- en: The deprecated attributes `_AXIS_NAMES` and `_AXIS_NUMBERS` of [`DataFrame`](../reference/api/pandas.DataFrame.html#pandas.DataFrame
    "pandas.DataFrame") and [`Series`](../reference/api/pandas.Series.html#pandas.Series
    "pandas.Series") will no longer show up in `dir` or `inspect.getmembers` calls
    ([GH 38740](https://github.com/pandas-dev/pandas/issues/38740))
  id: totrans-40
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: '[`DataFrame`](../reference/api/pandas.DataFrame.html#pandas.DataFrame "pandas.DataFrame")
    和 [`Series`](../reference/api/pandas.Series.html#pandas.Series "pandas.Series")
    的已弃用属性 `_AXIS_NAMES` 和 `_AXIS_NUMBERS` 将不再出现在 `dir` 或 `inspect.getmembers` 调用中
    ([GH 38740](https://github.com/pandas-dev/pandas/issues/38740))'
- en: Bumped minimum fastparquet version to 0.4.0 to avoid `AttributeError` from numba
    ([GH 38344](https://github.com/pandas-dev/pandas/issues/38344))
  id: totrans-41
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 将最小 fastparquet 版本提升到 0.4.0 以避免 numba 引发的 `AttributeError` ([GH 38344](https://github.com/pandas-dev/pandas/issues/38344))
- en: Bumped minimum pymysql version to 0.8.1 to avoid test failures ([GH 38344](https://github.com/pandas-dev/pandas/issues/38344))
  id: totrans-42
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 将最小 pymysql 版本提升到 0.8.1 以避免测试失败 ([GH 38344](https://github.com/pandas-dev/pandas/issues/38344))
- en: Fixed build failure on MacOS 11 in Python 3.9.1 ([GH 38766](https://github.com/pandas-dev/pandas/issues/38766))
  id: totrans-43
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 在 Python 3.9.1 中修复了在 MacOS 11 上的构建失败 ([GH 38766](https://github.com/pandas-dev/pandas/issues/38766))
- en: 'Added reference to backwards incompatible `check_freq` arg of [`testing.assert_frame_equal()`](../reference/api/pandas.testing.assert_frame_equal.html#pandas.testing.assert_frame_equal
    "pandas.testing.assert_frame_equal") and [`testing.assert_series_equal()`](../reference/api/pandas.testing.assert_series_equal.html#pandas.testing.assert_series_equal
    "pandas.testing.assert_series_equal") in [pandas 1.1.0 what’s new](v1.1.0.html#whatsnew-110-api-breaking-testing-check-freq)
    ([GH 34050](https://github.com/pandas-dev/pandas/issues/34050))  ## Contributors'
  id: totrans-44
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: '在 [pandas 1.1.0 新功能](v1.1.0.html#whatsnew-110-api-breaking-testing-check-freq)
    中为 [`testing.assert_frame_equal()`](../reference/api/pandas.testing.assert_frame_equal.html#pandas.testing.assert_frame_equal
    "pandas.testing.assert_frame_equal") 和 [`testing.assert_series_equal()`](../reference/api/pandas.testing.assert_series_equal.html#pandas.testing.assert_series_equal
    "pandas.testing.assert_series_equal") 添加了与后向不兼容的 `check_freq` 参数的引用 ([GH 34050](https://github.com/pandas-dev/pandas/issues/34050))  ##
    贡献者'
- en: A total of 20 people contributed patches to this release. People with a “+”
    by their names contributed a patch for the first time.
  id: totrans-45
  prefs: []
  type: TYPE_NORMAL
  zh: 总共有 20 人为此版本贡献了补丁。带有“+”标记的人首次贡献了补丁。
- en: Ada Draginda +
  id: totrans-46
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Ada Draginda +
- en: Andrew Wieteska
  id: totrans-47
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Andrew Wieteska
- en: Bryan Cutler
  id: totrans-48
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Bryan Cutler
- en: Fangchen Li
  id: totrans-49
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Fangchen Li
- en: Joris Van den Bossche
  id: totrans-50
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Joris Van den Bossche
- en: Matthew Roeschke
  id: totrans-51
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Matthew Roeschke
- en: Matthew Zeitlin +
  id: totrans-52
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Matthew Zeitlin +
- en: MeeseeksMachine
  id: totrans-53
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: MeeseeksMachine
- en: Micael Jarniac
  id: totrans-54
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Micael Jarniac
- en: Omar Afifi +
  id: totrans-55
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Omar Afifi +
- en: Pandas Development Team
  id: totrans-56
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Pandas 开发团队
- en: Richard Shadrach
  id: totrans-57
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Richard Shadrach
- en: Simon Hawkins
  id: totrans-58
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Simon Hawkins
- en: Terji Petersen
  id: totrans-59
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Terji Petersen
- en: Torsten Wörtwein
  id: totrans-60
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Torsten Wörtwein
- en: WANG Aiyong
  id: totrans-61
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: WANG Aiyong
- en: jbrockmendel
  id: totrans-62
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: jbrockmendel
- en: kylekeppler
  id: totrans-63
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: kylekeppler
- en: mzeitlin11
  id: totrans-64
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: mzeitlin11
- en: 'patrick  ## Fixed regressions'
  id: totrans-65
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 'patrick  ## 修复的回归问题'
- en: Fixed regression in [`to_csv()`](../reference/api/pandas.DataFrame.to_csv.html#pandas.DataFrame.to_csv
    "pandas.DataFrame.to_csv") that created corrupted zip files when there were more
    rows than `chunksize` ([GH 38714](https://github.com/pandas-dev/pandas/issues/38714))
  id: totrans-66
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了[`to_csv()`](../reference/api/pandas.DataFrame.to_csv.html#pandas.DataFrame.to_csv
    "pandas.DataFrame.to_csv")中的回归问题，当行数超过`chunksize`时会创建损坏的 zip 文件（[GH 38714](https://github.com/pandas-dev/pandas/issues/38714))
- en: Fixed regression in [`to_csv()`](../reference/api/pandas.DataFrame.to_csv.html#pandas.DataFrame.to_csv
    "pandas.DataFrame.to_csv") opening `codecs.StreamReaderWriter` in binary mode
    instead of in text mode ([GH 39247](https://github.com/pandas-dev/pandas/issues/39247))
  id: totrans-67
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了[`to_csv()`](../reference/api/pandas.DataFrame.to_csv.html#pandas.DataFrame.to_csv
    "pandas.DataFrame.to_csv")中的回归问题，以二进制模式而不是文本模式打开了`codecs.StreamReaderWriter`（[GH
    39247](https://github.com/pandas-dev/pandas/issues/39247))
- en: Fixed regression in [`read_csv()`](../reference/api/pandas.read_csv.html#pandas.read_csv
    "pandas.read_csv") and other read functions were the encoding error policy (`errors`)
    did not default to `"replace"` when no encoding was specified ([GH 38989](https://github.com/pandas-dev/pandas/issues/38989))
  id: totrans-68
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了[`read_csv()`](../reference/api/pandas.read_csv.html#pandas.read_csv "pandas.read_csv")和其他读取函数中的回归问题，当未指定编码时，编码错误策略
    (`errors`) 没有默认为`"replace"`（[GH 38989](https://github.com/pandas-dev/pandas/issues/38989))
- en: Fixed regression in [`read_excel()`](../reference/api/pandas.read_excel.html#pandas.read_excel
    "pandas.read_excel") with non-rawbyte file handles ([GH 38788](https://github.com/pandas-dev/pandas/issues/38788))
  id: totrans-69
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了使用非原始字节文件句柄时的[`read_excel()`](../reference/api/pandas.read_excel.html#pandas.read_excel
    "pandas.read_excel")中的回归问题（[GH 38788](https://github.com/pandas-dev/pandas/issues/38788))
- en: Fixed regression in [`DataFrame.to_stata()`](../reference/api/pandas.DataFrame.to_stata.html#pandas.DataFrame.to_stata
    "pandas.DataFrame.to_stata") not removing the created file when an error occurred
    ([GH 39202](https://github.com/pandas-dev/pandas/issues/39202))
  id: totrans-70
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了[`DataFrame.to_stata()`](../reference/api/pandas.DataFrame.to_stata.html#pandas.DataFrame.to_stata
    "pandas.DataFrame.to_stata")中的回归问题，当出现错误时未删除创建的文件（[GH 39202](https://github.com/pandas-dev/pandas/issues/39202))
- en: Fixed regression in `DataFrame.__setitem__` raising `ValueError` when expanding
    [`DataFrame`](../reference/api/pandas.DataFrame.html#pandas.DataFrame "pandas.DataFrame")
    and new column is from type `"0 - name"` ([GH 39010](https://github.com/pandas-dev/pandas/issues/39010))
  id: totrans-71
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了`DataFrame.__setitem__`中的回归问题，当扩展[`DataFrame`](../reference/api/pandas.DataFrame.html#pandas.DataFrame
    "pandas.DataFrame")并且新列的类型为`"0 - name"`时会引发`ValueError`（[GH 39010](https://github.com/pandas-dev/pandas/issues/39010))
- en: Fixed regression in setting with [`DataFrame.loc()`](../reference/api/pandas.DataFrame.loc.html#pandas.DataFrame.loc
    "pandas.DataFrame.loc") raising `ValueError` when [`DataFrame`](../reference/api/pandas.DataFrame.html#pandas.DataFrame
    "pandas.DataFrame") has unsorted [`MultiIndex`](../reference/api/pandas.MultiIndex.html#pandas.MultiIndex
    "pandas.MultiIndex") columns and indexer is a scalar ([GH 38601](https://github.com/pandas-dev/pandas/issues/38601))
  id: totrans-72
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了使用 [`DataFrame.loc()`](../reference/api/pandas.DataFrame.loc.html#pandas.DataFrame.loc
    "pandas.DataFrame.loc") 设置时引发`ValueError`的回归问题，当[`DataFrame`](../reference/api/pandas.DataFrame.html#pandas.DataFrame
    "pandas.DataFrame")具有未排序的[`MultiIndex`](../reference/api/pandas.MultiIndex.html#pandas.MultiIndex
    "pandas.MultiIndex")列且索引器为标量时（[GH 38601](https://github.com/pandas-dev/pandas/issues/38601))
- en: Fixed regression in setting with [`DataFrame.loc()`](../reference/api/pandas.DataFrame.loc.html#pandas.DataFrame.loc
    "pandas.DataFrame.loc") raising `KeyError` with [`MultiIndex`](../reference/api/pandas.MultiIndex.html#pandas.MultiIndex
    "pandas.MultiIndex") and list-like columns indexer enlarging [`DataFrame`](../reference/api/pandas.DataFrame.html#pandas.DataFrame
    "pandas.DataFrame") ([GH 39147](https://github.com/pandas-dev/pandas/issues/39147))
  id: totrans-73
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了使用 [`DataFrame.loc()`](../reference/api/pandas.DataFrame.loc.html#pandas.DataFrame.loc
    "pandas.DataFrame.loc") 设置时引发`KeyError`的回归问题，当使用[`MultiIndex`](../reference/api/pandas.MultiIndex.html#pandas.MultiIndex
    "pandas.MultiIndex")和类似列表的列索引器扩大 [`DataFrame`](../reference/api/pandas.DataFrame.html#pandas.DataFrame
    "pandas.DataFrame") 时（[GH 39147](https://github.com/pandas-dev/pandas/issues/39147))
- en: Fixed regression in [`groupby()`](../reference/api/pandas.DataFrame.groupby.html#pandas.DataFrame.groupby
    "pandas.DataFrame.groupby") with [`Categorical`](../reference/api/pandas.Categorical.html#pandas.Categorical
    "pandas.Categorical") grouping column not showing unused categories for `grouped.indices`
    ([GH 38642](https://github.com/pandas-dev/pandas/issues/38642))
  id: totrans-74
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了[`groupby()`](../reference/api/pandas.DataFrame.groupby.html#pandas.DataFrame.groupby
    "pandas.DataFrame.groupby")在使用[`Categorical`](../reference/api/pandas.Categorical.html#pandas.Categorical
    "pandas.Categorical")分组列时，对于`grouped.indices`未显示未使用类别的回归问题（[GH 38642](https://github.com/pandas-dev/pandas/issues/38642)）
- en: Fixed regression in [`DataFrameGroupBy.sem()`](../reference/api/pandas.core.groupby.DataFrameGroupBy.sem.html#pandas.core.groupby.DataFrameGroupBy.sem
    "pandas.core.groupby.DataFrameGroupBy.sem") and [`SeriesGroupBy.sem()`](../reference/api/pandas.core.groupby.SeriesGroupBy.sem.html#pandas.core.groupby.SeriesGroupBy.sem
    "pandas.core.groupby.SeriesGroupBy.sem") where the presence of non-numeric columns
    would cause an error instead of being dropped ([GH 38774](https://github.com/pandas-dev/pandas/issues/38774))
  id: totrans-75
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了[`DataFrameGroupBy.sem()`](../reference/api/pandas.core.groupby.DataFrameGroupBy.sem.html#pandas.core.groupby.DataFrameGroupBy.sem
    "pandas.core.groupby.DataFrameGroupBy.sem")和[`SeriesGroupBy.sem()`](../reference/api/pandas.core.groupby.SeriesGroupBy.sem.html#pandas.core.groupby.SeriesGroupBy.sem
    "pandas.core.groupby.SeriesGroupBy.sem")中存在非数值列会导致错误而不是被删除的回归问题（[GH 38774](https://github.com/pandas-dev/pandas/issues/38774)）
- en: Fixed regression in [`DataFrameGroupBy.diff()`](../reference/api/pandas.core.groupby.DataFrameGroupBy.diff.html#pandas.core.groupby.DataFrameGroupBy.diff
    "pandas.core.groupby.DataFrameGroupBy.diff") raising for `int8` and `int16` columns
    ([GH 39050](https://github.com/pandas-dev/pandas/issues/39050))
  id: totrans-76
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了[`DataFrameGroupBy.diff()`](../reference/api/pandas.core.groupby.DataFrameGroupBy.diff.html#pandas.core.groupby.DataFrameGroupBy.diff
    "pandas.core.groupby.DataFrameGroupBy.diff")在处理`int8`和`int16`列时引发错误的回归问题（[GH 39050](https://github.com/pandas-dev/pandas/issues/39050)）
- en: Fixed regression in [`DataFrame.groupby()`](../reference/api/pandas.DataFrame.groupby.html#pandas.DataFrame.groupby
    "pandas.DataFrame.groupby") when aggregating an `ExtensionDType` that could fail
    for non-numeric values ([GH 38980](https://github.com/pandas-dev/pandas/issues/38980))
  id: totrans-77
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了[`DataFrame.groupby()`](../reference/api/pandas.DataFrame.groupby.html#pandas.DataFrame.groupby
    "pandas.DataFrame.groupby")在聚合`ExtensionDType`时对非数值值可能失败的回归问题（[GH 38980](https://github.com/pandas-dev/pandas/issues/38980)）
- en: Fixed regression in [`Rolling.skew()`](../reference/api/pandas.core.window.rolling.Rolling.skew.html#pandas.core.window.rolling.Rolling.skew
    "pandas.core.window.rolling.Rolling.skew") and [`Rolling.kurt()`](../reference/api/pandas.core.window.rolling.Rolling.kurt.html#pandas.core.window.rolling.Rolling.kurt
    "pandas.core.window.rolling.Rolling.kurt") modifying the object inplace ([GH 38908](https://github.com/pandas-dev/pandas/issues/38908))
  id: totrans-78
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了[`Rolling.skew()`](../reference/api/pandas.core.window.rolling.Rolling.skew.html#pandas.core.window.rolling.Rolling.skew
    "pandas.core.window.rolling.Rolling.skew")和[`Rolling.kurt()`](../reference/api/pandas.core.window.rolling.Rolling.kurt.html#pandas.core.window.rolling.Rolling.kurt
    "pandas.core.window.rolling.Rolling.kurt")在原地修改对象的回归问题（[GH 38908](https://github.com/pandas-dev/pandas/issues/38908))
- en: Fixed regression in [`DataFrame.any()`](../reference/api/pandas.DataFrame.any.html#pandas.DataFrame.any
    "pandas.DataFrame.any") and [`DataFrame.all()`](../reference/api/pandas.DataFrame.all.html#pandas.DataFrame.all
    "pandas.DataFrame.all") not returning a result for tz-aware `datetime64` columns
    ([GH 38723](https://github.com/pandas-dev/pandas/issues/38723))
  id: totrans-79
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了[`DataFrame.any()`](../reference/api/pandas.DataFrame.any.html#pandas.DataFrame.any
    "pandas.DataFrame.any")和[`DataFrame.all()`](../reference/api/pandas.DataFrame.all.html#pandas.DataFrame.all
    "pandas.DataFrame.all")在处理带有时区信息的`datetime64`列时未返回结果的回归问题（[GH 38723](https://github.com/pandas-dev/pandas/issues/38723)）
- en: Fixed regression in [`DataFrame.apply()`](../reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply
    "pandas.DataFrame.apply") with `axis=1` using str accessor in apply function ([GH
    38979](https://github.com/pandas-dev/pandas/issues/38979))
  id: totrans-80
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了[`DataFrame.apply()`](../reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply
    "pandas.DataFrame.apply")在使用`axis=1`时，在应用函数中使用str访问器时引发错误的回归问题（[GH 38979](https://github.com/pandas-dev/pandas/issues/38979)）
- en: Fixed regression in [`DataFrame.replace()`](../reference/api/pandas.DataFrame.replace.html#pandas.DataFrame.replace
    "pandas.DataFrame.replace") raising `ValueError` when [`DataFrame`](../reference/api/pandas.DataFrame.html#pandas.DataFrame
    "pandas.DataFrame") has dtype `bytes` ([GH 38900](https://github.com/pandas-dev/pandas/issues/38900))
  id: totrans-81
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了[`DataFrame.replace()`](../reference/api/pandas.DataFrame.replace.html#pandas.DataFrame.replace
    "pandas.DataFrame.replace")在[`DataFrame`](../reference/api/pandas.DataFrame.html#pandas.DataFrame
    "pandas.DataFrame")的dtype为`bytes`时引发`ValueError`的回归问题（[GH 38900](https://github.com/pandas-dev/pandas/issues/38900)）
- en: Fixed regression in [`Series.fillna()`](../reference/api/pandas.Series.fillna.html#pandas.Series.fillna
    "pandas.Series.fillna") that raised `RecursionError` with `datetime64[ns, UTC]`
    dtype ([GH 38851](https://github.com/pandas-dev/pandas/issues/38851))
  id: totrans-82
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了在 [`Series.fillna()`](../reference/api/pandas.Series.fillna.html#pandas.Series.fillna
    "pandas.Series.fillna") 中使用 `datetime64[ns, UTC]` dtype 时引发 `RecursionError` 的回归问题（[GH
    38851](https://github.com/pandas-dev/pandas/issues/38851))
- en: Fixed regression in comparisons between `NaT` and `datetime.date` objects incorrectly
    returning `True` ([GH 39151](https://github.com/pandas-dev/pandas/issues/39151))
  id: totrans-83
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了 `NaT` 和 `datetime.date` 对象之间比较错误地返回 `True` 的回归问题（[GH 39151](https://github.com/pandas-dev/pandas/issues/39151))
- en: Fixed regression in calling NumPy `accumulate()` ufuncs on DataFrames, e.g.
    `np.maximum.accumulate(df)` ([GH 39259](https://github.com/pandas-dev/pandas/issues/39259))
  id: totrans-84
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了在 DataFrames 上调用 NumPy `accumulate()` ufuncs 时的回归问题，例如 `np.maximum.accumulate(df)`（[GH
    39259](https://github.com/pandas-dev/pandas/issues/39259))
- en: Fixed regression in repr of float-like strings of an `object` dtype having trailing
    0’s truncated after the decimal ([GH 38708](https://github.com/pandas-dev/pandas/issues/38708))
  id: totrans-85
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了在 `object` dtype 中浮点类似字符串的 repr 中，小数点后的尾随 0 被截断的回归问题（[GH 38708](https://github.com/pandas-dev/pandas/issues/38708))
- en: Fixed regression that raised `AttributeError` with PyArrow versions [0.16.0,
    1.0.0) ([GH 38801](https://github.com/pandas-dev/pandas/issues/38801))
  id: totrans-86
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了在 PyArrow 版本 [0.16.0, 1.0.0) 中引发 `AttributeError` 的回归问题（[GH 38801](https://github.com/pandas-dev/pandas/issues/38801))
- en: Fixed regression in [`pandas.testing.assert_frame_equal()`](../reference/api/pandas.testing.assert_frame_equal.html#pandas.testing.assert_frame_equal
    "pandas.testing.assert_frame_equal") raising `TypeError` with `check_like=True`
    when [`Index`](../reference/api/pandas.Index.html#pandas.Index "pandas.Index")
    or columns have mixed dtype ([GH 39168](https://github.com/pandas-dev/pandas/issues/39168))
  id: totrans-87
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了在 [`pandas.testing.assert_frame_equal()`](../reference/api/pandas.testing.assert_frame_equal.html#pandas.testing.assert_frame_equal
    "pandas.testing.assert_frame_equal") 中使用 `check_like=True` 时，当 [`Index`](../reference/api/pandas.Index.html#pandas.Index
    "pandas.Index") 或列具有混合 dtype 时引发 `TypeError` 的回归问题（[GH 39168](https://github.com/pandas-dev/pandas/issues/39168))
- en: We have reverted a commit that resulted in several plotting related regressions
    in pandas 1.2.0 ([GH 38969](https://github.com/pandas-dev/pandas/issues/38969),
    [GH 38736](https://github.com/pandas-dev/pandas/issues/38736), [GH 38865](https://github.com/pandas-dev/pandas/issues/38865),
    [GH 38947](https://github.com/pandas-dev/pandas/issues/38947) and [GH 39126](https://github.com/pandas-dev/pandas/issues/39126)).
    As a result, bugs reported as fixed in pandas 1.2.0 related to inconsistent tick
    labeling in bar plots are again present ([GH 26186](https://github.com/pandas-dev/pandas/issues/26186)
    and [GH 11465](https://github.com/pandas-dev/pandas/issues/11465))
  id: totrans-88
  prefs: []
  type: TYPE_NORMAL
  zh: 我们已经回滚了一个提交，导致了 pandas 1.2.0 中几个与绘图相关的回归问题（[GH 38969](https://github.com/pandas-dev/pandas/issues/38969)，[GH
    38736](https://github.com/pandas-dev/pandas/issues/38736)，[GH 38865](https://github.com/pandas-dev/pandas/issues/38865)，[GH
    38947](https://github.com/pandas-dev/pandas/issues/38947) 和 [GH 39126](https://github.com/pandas-dev/pandas/issues/39126)）。因此，在
    pandas 1.2.0 中报告为已修复的与条形图中标签不一致的错误再次出现（[GH 26186](https://github.com/pandas-dev/pandas/issues/26186)
    和 [GH 11465](https://github.com/pandas-dev/pandas/issues/11465))
- en: '## Calling NumPy ufuncs on non-aligned DataFrames'
  id: totrans-89
  prefs: []
  type: TYPE_NORMAL
  zh: '## 在非对齐的 DataFrames 上调用 NumPy ufuncs'
- en: 'Before pandas 1.2.0, calling a NumPy ufunc on non-aligned DataFrames (or DataFrame
    / Series combination) would ignore the indices, only match the inputs by shape,
    and use the index/columns of the first DataFrame for the result:'
  id: totrans-90
  prefs: []
  type: TYPE_NORMAL
  zh: 在 pandas 1.2.0 之前，在非对齐的 DataFrames（或 DataFrame / Series 组合）上调用 NumPy ufunc 会忽略索引，仅按形状匹配输入，并使用第一个
    DataFrame 的索引/列作为结果：
- en: '[PRE4]'
  id: totrans-91
  prefs: []
  type: TYPE_PRE
  zh: '[PRE4]'
- en: 'This contrasts with how other pandas operations work, which first align the
    inputs:'
  id: totrans-92
  prefs: []
  type: TYPE_NORMAL
  zh: 这与其他 pandas 操作的工作方式相反，其他操作首先对齐输入：
- en: '[PRE5]'
  id: totrans-93
  prefs: []
  type: TYPE_PRE
  zh: '[PRE5]'
- en: In pandas 1.2.0, we refactored how NumPy ufuncs are called on DataFrames, and
    this started to align the inputs first ([GH 39184](https://github.com/pandas-dev/pandas/issues/39184)),
    as happens in other pandas operations and as it happens for ufuncs called on Series
    objects.
  id: totrans-94
  prefs: []
  type: TYPE_NORMAL
  zh: 在 pandas 1.2.0 中，我们重构了如何在 DataFrames 上调用 NumPy ufuncs，并且这开始首先对齐输入（[GH 39184](https://github.com/pandas-dev/pandas/issues/39184)），就像其他
    pandas 操作和在 Series 对象上调用 ufuncs 时一样。
- en: For pandas 1.2.1, we restored the previous behaviour to avoid a breaking change,
    but the above example of `np.add(df1, df2)` with non-aligned inputs will now to
    raise a warning, and a future pandas 2.0 release will start aligning the inputs
    first ([GH 39184](https://github.com/pandas-dev/pandas/issues/39184)). Calling
    a NumPy ufunc on Series objects (eg `np.add(s1, s2)`) already aligns and continues
    to do so.
  id: totrans-95
  prefs: []
  type: TYPE_NORMAL
  zh: 对于 pandas 1.2.1，我们恢复了先前的行为以避免破坏性更改，但上述示例中的 `np.add(df1, df2)` 使用非对齐输入将会引发警告，未来的
    pandas 2.0 版本将首先对齐输入（[GH 39184](https://github.com/pandas-dev/pandas/issues/39184)）。在
    Series 对象上调用 NumPy ufunc（例如 `np.add(s1, s2)`）已经对齐并将继续这样做。
- en: 'To avoid the warning and keep the current behaviour of ignoring the indices,
    convert one of the arguments to a NumPy array:'
  id: totrans-96
  prefs: []
  type: TYPE_NORMAL
  zh: 为了避免警告并保持忽略索引的当前行为，将其中一个参数转换为NumPy数组：
- en: '[PRE6]'
  id: totrans-97
  prefs: []
  type: TYPE_PRE
  zh: '[PRE6]'
- en: 'To obtain the future behaviour and silence the warning, you can align manually
    before passing the arguments to the ufunc:'
  id: totrans-98
  prefs: []
  type: TYPE_NORMAL
  zh: 要获得未来行为并消除警告，您可以在将参数传递给 ufunc 之前手动对齐：
- en: '[PRE7]'
  id: totrans-99
  prefs: []
  type: TYPE_PRE
  zh: '[PRE7]'
- en: '## Bug fixes'
  id: totrans-100
  prefs: []
  type: TYPE_NORMAL
  zh: '## Bug 修复'
- en: Bug in [`read_csv()`](../reference/api/pandas.read_csv.html#pandas.read_csv
    "pandas.read_csv") with `float_precision="high"` caused segfault or wrong parsing
    of long exponent strings. This resulted in a regression in some cases as the default
    for `float_precision` was changed in pandas 1.2.0 ([GH 38753](https://github.com/pandas-dev/pandas/issues/38753))
  id: totrans-101
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 在 `float_precision="high"` 的情况下 [`read_csv()`](../reference/api/pandas.read_csv.html#pandas.read_csv
    "pandas.read_csv") 中的错误导致 segfault 或长指数字符串的错误解析。这在某些情况下导致了回归，因为 `float_precision`
    的默认值在 pandas 1.2.0 中已更改（[GH 38753](https://github.com/pandas-dev/pandas/issues/38753)）
- en: Bug in [`read_csv()`](../reference/api/pandas.read_csv.html#pandas.read_csv
    "pandas.read_csv") not closing an opened file handle when a `csv.Error` or `UnicodeDecodeError`
    occurred while initializing ([GH 39024](https://github.com/pandas-dev/pandas/issues/39024))
  id: totrans-102
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 在初始化时 [`read_csv()`](../reference/api/pandas.read_csv.html#pandas.read_csv "pandas.read_csv")
    出现 `csv.Error` 或 `UnicodeDecodeError` 时未关闭已打开的文件句柄的错误（[GH 39024](https://github.com/pandas-dev/pandas/issues/39024)）
- en: Bug in [`pandas.testing.assert_index_equal()`](../reference/api/pandas.testing.assert_index_equal.html#pandas.testing.assert_index_equal
    "pandas.testing.assert_index_equal") raising `TypeError` with `check_order=False`
    when [`Index`](../reference/api/pandas.Index.html#pandas.Index "pandas.Index")
    has mixed dtype ([GH 39168](https://github.com/pandas-dev/pandas/issues/39168))
  id: totrans-103
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 在 [`pandas.testing.assert_index_equal()`](../reference/api/pandas.testing.assert_index_equal.html#pandas.testing.assert_index_equal
    "pandas.testing.assert_index_equal") 中的错误，当 [`Index`](../reference/api/pandas.Index.html#pandas.Index
    "pandas.Index") 具有混合 dtype 时，使用 `check_order=False` 会引发 `TypeError`（[GH 39168](https://github.com/pandas-dev/pandas/issues/39168)）
- en: '## Other'
  id: totrans-104
  prefs: []
  type: TYPE_NORMAL
  zh: '## 其他'
- en: The deprecated attributes `_AXIS_NAMES` and `_AXIS_NUMBERS` of [`DataFrame`](../reference/api/pandas.DataFrame.html#pandas.DataFrame
    "pandas.DataFrame") and [`Series`](../reference/api/pandas.Series.html#pandas.Series
    "pandas.Series") will no longer show up in `dir` or `inspect.getmembers` calls
    ([GH 38740](https://github.com/pandas-dev/pandas/issues/38740))
  id: totrans-105
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 已弃用的 [`DataFrame`](../reference/api/pandas.DataFrame.html#pandas.DataFrame "pandas.DataFrame")
    和 [`Series`](../reference/api/pandas.Series.html#pandas.Series "pandas.Series")
    的属性 `_AXIS_NAMES` 和 `_AXIS_NUMBERS` 将不再出现在 `dir` 或 `inspect.getmembers` 调用中（[GH
    38740](https://github.com/pandas-dev/pandas/issues/38740)）
- en: Bumped minimum fastparquet version to 0.4.0 to avoid `AttributeError` from numba
    ([GH 38344](https://github.com/pandas-dev/pandas/issues/38344))
  id: totrans-106
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 将最小的 fastparquet 版本提升到 0.4.0 以避免 numba 的 `AttributeError`（[GH 38344](https://github.com/pandas-dev/pandas/issues/38344)）
- en: Bumped minimum pymysql version to 0.8.1 to avoid test failures ([GH 38344](https://github.com/pandas-dev/pandas/issues/38344))
  id: totrans-107
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 将最小的 pymysql 版本提升到 0.8.1 以避免测试失败（[GH 38344](https://github.com/pandas-dev/pandas/issues/38344)）
- en: Fixed build failure on MacOS 11 in Python 3.9.1 ([GH 38766](https://github.com/pandas-dev/pandas/issues/38766))
  id: totrans-108
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 修复了在 Python 3.9.1 中在 MacOS 11 上构建失败的问题（[GH 38766](https://github.com/pandas-dev/pandas/issues/38766)）
- en: Added reference to backwards incompatible `check_freq` arg of [`testing.assert_frame_equal()`](../reference/api/pandas.testing.assert_frame_equal.html#pandas.testing.assert_frame_equal
    "pandas.testing.assert_frame_equal") and [`testing.assert_series_equal()`](../reference/api/pandas.testing.assert_series_equal.html#pandas.testing.assert_series_equal
    "pandas.testing.assert_series_equal") in [pandas 1.1.0 what’s new](v1.1.0.html#whatsnew-110-api-breaking-testing-check-freq)
    ([GH 34050](https://github.com/pandas-dev/pandas/issues/34050))
  id: totrans-109
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 在 [pandas 1.1.0 新功能](v1.1.0.html#whatsnew-110-api-breaking-testing-check-freq)
    中的 [`testing.assert_frame_equal()`](../reference/api/pandas.testing.assert_frame_equal.html#pandas.testing.assert_frame_equal
    "pandas.testing.assert_frame_equal") 和 [`testing.assert_series_equal()`](../reference/api/pandas.testing.assert_series_equal.html#pandas.testing.assert_series_equal
    "pandas.testing.assert_series_equal") 中添加了对不兼容的 `check_freq` 参数的引用（[GH 34050](https://github.com/pandas-dev/pandas/issues/34050)）
- en: '## Contributors'
  id: totrans-110
  prefs: []
  type: TYPE_NORMAL
  zh: '## 贡献者'
- en: A total of 20 people contributed patches to this release. People with a “+”
    by their names contributed a patch for the first time.
  id: totrans-111
  prefs: []
  type: TYPE_NORMAL
  zh: 本次发布中共有20人贡献了补丁。名字旁边带有“+”符号的人第一次贡献了补丁。
- en: Ada Draginda +
  id: totrans-112
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Ada Draginda +
- en: Andrew Wieteska
  id: totrans-113
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Andrew Wieteska
- en: Bryan Cutler
  id: totrans-114
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Bryan Cutler
- en: Fangchen Li
  id: totrans-115
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Fangchen Li
- en: Joris Van den Bossche
  id: totrans-116
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Joris Van den Bossche
- en: Matthew Roeschke
  id: totrans-117
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Matthew Roeschke
- en: Matthew Zeitlin +
  id: totrans-118
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Matthew Zeitlin +
- en: MeeseeksMachine
  id: totrans-119
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: MeeseeksMachine
- en: Micael Jarniac
  id: totrans-120
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Micael Jarniac
- en: Omar Afifi +
  id: totrans-121
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Omar Afifi +
- en: Pandas Development Team
  id: totrans-122
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Pandas开发团队
- en: Richard Shadrach
  id: totrans-123
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Richard Shadrach
- en: Simon Hawkins
  id: totrans-124
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Simon Hawkins
- en: Terji Petersen
  id: totrans-125
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Terji Petersen
- en: Torsten Wörtwein
  id: totrans-126
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Torsten Wörtwein
- en: WANG Aiyong
  id: totrans-127
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 王爱勇
- en: jbrockmendel
  id: totrans-128
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: jbrockmendel
- en: kylekeppler
  id: totrans-129
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: kylekeppler
- en: mzeitlin11
  id: totrans-130
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: mzeitlin11
- en: patrick
  id: totrans-131
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: patrick
