- en: scipy.linalg.LinAlgError
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 原文：[https://docs.scipy.org/doc/scipy-1.12.0/reference/generated/scipy.linalg.LinAlgError.html#scipy.linalg.LinAlgError](https://docs.scipy.org/doc/scipy-1.12.0/reference/generated/scipy.linalg.LinAlgError.html#scipy.linalg.LinAlgError)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: '[PRE0]'
  prefs: []
  type: TYPE_PRE
- en: Generic Python-exception-derived object raised by linalg functions.
  prefs: []
  type: TYPE_NORMAL
- en: General purpose exception class, derived from Python’s ValueError class, programmatically
    raised in linalg functions when a Linear Algebra-related condition would prevent
    further correct execution of the function.
  prefs: []
  type: TYPE_NORMAL
- en: 'Parameters:'
  prefs: []
  type: TYPE_NORMAL
- en: '**None**'
  prefs: []
  type: TYPE_NORMAL
- en: Examples
  prefs: []
  type: TYPE_NORMAL
- en: '[PRE1]'
  prefs: []
  type: TYPE_PRE
- en: '[PRE2]'
  prefs: []
  type: TYPE_PRE
- en: Exception.with_traceback(tb) – set self.__traceback__ to tb and return self.
  prefs: []
  type: TYPE_NORMAL
